config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'
  get 'tweets', to: 'tweets#index'
  post 'tweets', to: 'tweets#create'
  delete 'tweets/:id', to: 'tweets#destroy', as: 'delete_tweet'

  get '/auth/twitter/callback', to: 'sessions#create'
  delete 'sessions/destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :body, presence: true
  validates_length_of :body, maximum: 280
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = OauthService.find_or_create_user(auth_hash)
    session[:user_id] = @user.id
    flash[:success] = 'You was successfully authorized'
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You was successfully logged out'
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_client, only: %i[create destroy], if: :current_user
  before_action :set_vars, if: :current_user

  def index; end

  def create
    @tweet.user_id = current_user.id
    image = nil
    image = File.new(params[:tweet][:image].tempfile) if params[:tweet][:image]
    if @tweet.valid?
      post_tweet(@tweet, image)
    else
      flash[:error] = 'Tweet is not valid!'
      render :index
    end
  end

  def destroy
    @tweet = current_user.tweets.find(params[:id])
    delete_tweet(@tweet)
    @tweet.destroy
    redirect_to root_path
  end

  private

  def tweet_params
    params.fetch(:tweet, {}).permit(:body)
  end

  def set_client
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['API_KEY']
      config.consumer_secret     = ENV['API_SECRET']
      config.access_token        = @current_user.token
      config.access_token_secret = @current_user.secret
    end
  end

  def set_vars
    @tweet = Tweet.new(tweet_params)
    @tweets = current_user.tweets.order(created_at: :desc)
  end

  def post_tweet(tweet, image)
    if image
      posted = @client.update_with_media(tweet.body, image)
      tweet.image = posted.media[0].media_url.to_s
    else
      posted = @client.update(tweet.body)
    end
    tweet.tid = posted.id
    tweet.save
    flash[:success] = 'Tweet was successfully published!'
    redirect_to root_path
  rescue StandardError
    flash[:error] = 'Error in posting tweet to Twitter'
    tweet.errors[:base] << 'Error in posting tweet to Twitter'
    render :index
  end

  def delete_tweet(tweet)
    @client.destroy_status(tweet.tid)
    flash[:notice] = 'Tweet was successfully deleted'
  rescue StandardError
    flash[:error] = "Couldn't delete tweet from Twitter"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_path
    '/auth/twitter'
  end

  def bootstrap_class_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info' }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div,
                         message,
                         class: "alert #{bootstrap_class_for(msg_type)}",
                         role: 'alert') do
               concat(content_tag(:button,
                                  'x', class: 'close',
                                       data: { dismiss: 'alert' }))
               concat(message)
             end)
    end
    nil
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def tweet_path(tid)
    "https://twitter.com/#{current_user.nickname}/status/#{tid}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash_messages %>
    <nav class="navbar sticky-top navbar-light bg-white shadow-sm mb-3">
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag('twitter.svg', width: 30, height: 30) %>
        Tweet manager
      </a>
      <div class="form-inline">
        <% if current_user %>
          <div class="dropdown">
             <button class="btn bg-white dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag(current_user.image, class: 'rounded-circle') %>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="https://twitter.com/<%=current_user.nickname%>">@<%= current_user.nickname %></a>
              <div class="dropdown-divider"></div>
              <%= link_to 'Logout', sessions_destroy_path, :method => 'delete', class: 'dropdown-item' %>
            </div>
          </div>
        <% else %>
          <%= link_to 'Login', login_path, class: "btn btn-success text-white" %>
        <% end %>
      </div>
    </nav>
    <div class="container text-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/index.html.erb
<% if !current_user %>
  <div class="jumbotron">
    <h1 class="display-4"> To access this section you need to <%= link_to 'authenticate', login_path %> 😉</h1>
  </div>
<% else %>
  <%= form_for @tweet, url: { action: :create }, multipart: true do |tweet_form| %>
    <% if @tweet.errors.any? %>
      <div class="alert alert-danger text-left">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div id="errorExplanation">
          <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being published:</h2>
          <ul>
          <% @tweet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <div class="d-flex justify-content-center">
      <div class="p-2">
        <%= tweet_form.text_area :body, maxlength: 280, cols: 50, rows: 6, placeholder: "What's happening?", class: 'form-control' %>
        <span class="btn btn-large btn-primary btn-file w-100">
          Upload image
          <%= tweet_form.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
        </span>
      </div>
      <div class="align-self-center">
        <%= tweet_form.submit 'Tweet!', class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>

  <% for tweet in @tweets %>
    <div class="card mx-auto mw-100 mb-4" style="width: 600px;">
      <button type="button" class="close" aria-label="Close">
        <%= link_to '<span aria-hidden="true" class="float-right mr-1">&times;</span>'.html_safe, delete_tweet_path(tweet), method: :delete, data: { confirm: 'Are you sure?' } %>
      </button>
      <div class="card-body pt-0">
        <div class="card-text">
          <%= tweet.body %>
        </div>
        <% if tweet.image %>
          <%= image_tag(tweet.image, class: 'card-img-bottom mt-2') %>
        <% end %>
        <div class="float-right mt-2">
          <span class="text-secondary"><%= tweet.created_at.in_time_zone(3).strftime('%d.%m.%Y %H:%M') %></span>
          <%= link_to 'View', tweet_path(tweet.tid), class: 'card-link pl-4', target: :_blank %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>